# Project Euler Notebook
Welcome to my little notebook server where you can try to solve problems from project Euler.

[![project euler](https://projecteuler.net/themes/logo_default.png)](https://www.projecteuler.net)

## Problem 1 - Multiples of 3 or 5
If we list all the natural numbers below $10$ that are multiples of $3$ or $5$, we get $3, 5, 6$ and $9$. The sum of these multiples is $23$.

Find the sum of all the multiples of $3$ or $5$ below $1000$.

In [1]:
import numpy as np
import sys

In [2]:
#your solution

## Problem 2 - Even Fibonacci Numbers

<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>

In [ ]:
prev = 1
current = 1
fib = []
while current < 4000000:
    fib.append(current)
    next_fib = prev+current
    prev = current
    current = next_fib

## Problem 3 - Largest Prime Factor

<p>The prime factors of $13195$ are $5, 7, 13$ and $29$.</p>
<p>What is the largest prime factor of the number $600851475143$?</p>

In [4]:
def largest_prime_factor(n):
    factors = []
    denom = 2
    while n!=1:
        if n%denom==0:
            n//=denom
            factors.append(denom)
        else:
            denom+=1
    return(np.max(factors))

In [5]:
%time
largest_prime_factor(600851475143)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 0 ns

6857

## Problem 4 - Largest Palindrome Product

<p>A palindromic number reads the same both ways. The largest palindrome made from the product of two $2$-digit numbers is $9009 = 91 \times 99$.</p>
<p>Find the largest palindrome made from the product of two $3$-digit numbers.</p>

In [6]:
def check_palindrome(x: str):
    if x[::-1] == x:
        return True
    else:
        return False
    
def find_largest_palindrome():
    largest_palindrome = 0
    for i in range(100, 1000):
        for j in range(i, 1000):
            product = i*j
            if check_palindrome(str(product)) and product>largest_palindrome:
                largest_palindrome = product
    return largest_palindrome

In [7]:
%time
find_largest_palindrome()

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 0 ns

906609

## Problem 5 - Smallest Multiple


<p>$2520$ is the smallest number that can be divided by each of the numbers from $1$ to $10$ without any remainder.</p>
<p>What is the smallest positive number that is <dfn class="tooltip">evenly divisible<span class="tooltiptext">divisible with no remainder</span></dfn> by all of the numbers from $1$ to $20$?</p>

In [1]:
def find_least_common_multiple(lower: int, upper: int) -> int:
    """returns the smallest integer that is divisible by both numbers"""
    common_multiple = upper
    while common_multiple%lower!=0:
        common_multiple += upper
    return common_multiple

In [2]:
def find_smallest_multiple(up_to: int = 20) -> int:
    """find the smallest multiple by iteratively finding the least common multiple of the increasing values"""
    multiple = 1
    for i in range(2, up_to+1):
        multiple = find_least_common_multiple(multiple, i)
    return multiple

In [4]:
find_smallest_multiple(up_to = 20)

232792560

In [12]:
import time
import matplotlib.pyplot as plt

def time_smallest_multiple(up_to = 20):
    times = []
    for i in range(2, up_to+1):
        start_time = time.time()
        multiple = find_smallest_multiple(up_to = i)
        end_time = time.time()
        times.append(end_time-start_time)
    return times

In [ ]:
times = time_smallest_multiple(24)
ns = range(1, 22)

In [ ]:
fig, ax = plt.subplots()
ax.plot(ns, times)
ax.scatter(ns, times, color = "r")
ax.set_xticks(ns)